const Map<String, dynamic> titlePage = {
  'dashboard': 'Dashboard',
  'dotdangkiPage': 'D/s đợt đăng kí',
  'dotdangkiPage/editDotdangkiScreen': 'D/s đợt đăng kí',
  'dotdangkiPage/selectNganhdangkiScreen': 'D/s đợt đăng kí',
  'dotdangkiPage/addDotdangkiScreen': 'D/s đợt đăng kí',
  'hosodangkiPage': 'Hồ sơ đăng kí',
  'thulephidangkiPage': 'Thu lệ phí đăng kí',
  'xettuyenPage': 'Xét tuyển',
  'hosotrungtuyenPage': 'Hồ sơ trúng tuyển',
  'hosokhongdudkttPage': 'Hồ sơ không đủ ĐKTT',
  'thulephinhaphocPage': 'Thu lệ phí nhập học',
  'thuhosonhaphocPage': 'Thu hồ sơ nhập học',
  'hosonhaphocPage': 'Hồ sơ nhập học',
  'danhmucPage': 'Danh mục',
  'danhmucPage/cosoPage': 'Danh sách cơ sở',
  'danhmucPage/doituongPage': 'Danh sách đối tượng',
  'danhmucPage/hedaotaoPage': 'Danh sách hệ đào tạo',
  'danhmucPage/khoaPage': 'Danh sách khoa',
  'danhmucPage/kinhphinhaphocPage': 'Danh sách kinh phí nhập học',
  'danhmucPage/lopPage': 'Danh sách lớp',
  'danhmucPage/nganhPage': 'Danh sách ngành',
  'danhmucPage/tohopxettuyenPage': 'Danh sách tổ hợp',
  'bangkePage': 'Bảng kê',
  'bangkePage/kinhphinhaphocPage': 'Kinh phí nhập học',
  'bangkePage/lephinhaphocPage': 'Lệ phí nhập học',
  'bangkePage/nhaphoctheonganhPage': 'Nhập học theo ngành',
  'hethongPage': 'Hệ thống',
};
